### ISSUE TITLE
Data Base scheme

### ISSUE THREAD

**Issue by daniilkrant** [AndrewArs/Computer-accounting#1]
Can you please provide this DB scheme as well?

**Comment by AndrewArs** [comment]
![image](https://user-images.githubusercontent.com/13135703/34850196-9226976a-f72d-11e7-9722-cdb27977d119.png)

**Comment by daniilkrant** [comment]
Oookey, thanks a lot!, mb you can send me a DB file to 
danbiil988@gmail.com
?

**Comment by daniilkrant** [comment]
Oky, sorry) Thanks a lot)
